// <auto-generated />
namespace HospitalProject_HTTP5212.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class doctorpatient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doctorpatient));
        
        string IMigrationMetadata.Id
        {
            get { return "202204231720481_doctor-patient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
