// <auto-generated />
namespace HospitalProject_HTTP5212.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class doctors : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doctors));
        
        string IMigrationMetadata.Id
        {
            get { return "202204231703567_doctors"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
