// <auto-generated />
namespace HospitalProject_HTTP5212.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class doctorspeciality : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(doctorspeciality));
        
        string IMigrationMetadata.Id
        {
            get { return "202204232210183_doctor-speciality"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
